---
- name: Configuring tomcat
  hosts: all
  tasks:
    - name: Install tomcat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: no}
    - name: Copy modified tomcat user .xml file
      copy:
        src: /home/ubuntu/tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted
    - name: pause tomcat to check after restart
      pause:
        seconds: 60
    - name: check status of tomcat port
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.17.156:9090
        - http://172.31.22.96:9090
...
