---
- name: Configuring nginx
  hosts: all
  tasks:
    - name: Installing nginx 
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Edit the index.html file
      copy:
        src: /home/ubuntu/ansible_playbooks/index.nginx-debian.html 
        dest: /var/www/html
      notify: restart service
    - name: This playbook is replaced by
      debug:
        msg: "playbook28 in the notes"
  handlers:
    - name: restart service
      service:
        name: nginx
        state: restarted
...
# this playbook is replcing playbook28 explained in class 
