---
- name: Create users and diresctories is user home dir and copy the passwd file and change permissions
  hosts: all
  tasks:
    - name: create user
      user:
        name: Ravi
        password: intelliqit
        home: /tmp/Ravi
    - name: Create dir in users home directory
      file:
        name: /tmp/Ravi/dir1
        state: directory
    - name: Copy the passwd file
      copy:
        src: /etc/passwd
        dest: /tmp/Ravi/dir1
    - name: change permissions of the file
      file:
        name: /tmp/Ravi/dir1/passwd
        mode: 760 
...
