---
- name: Tmplementing host scope variables
  hosts: 172.31.17.156
  tasks:
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...
