---
- name: Implemnting tags
  hosts: all
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
      tags: 
        - git_installation
        - always        
    - name: Create user
      user:
        name: Anu
        password: intelliqit
      tags: user_creation
    - name: Copy passwd fil
      copy:
        src: /etc/passwd
        dest: /tmp
...
