---
- name: Create user on all servers
  hosts: all
  tasks:
    - name: User creation
      user:
        name: hman 
        password: intelliqit
        home: /tmp/hman
        shell: /bin/bash
        comment: "A regular user"
        uid: 6789
...



