---
# handlers file for nginx
- name: restart service
  service:
    name: "{{pkg1}}"
    state: "{{state2}}"
- name: check response
  uri:
    url: "{{item.a}}"
    status_code: "{{item.b}}"
  with_items:
    - {a: "{{server1}}",b: "{{status1}}"}
    - {a: "{{server2}}",b: "{{status1}}"}
...
   
